### ISSUE TITLE
ModuleNotFoundError: No module named 'GRF'

### ISSUE THREAD

**Issue by wongsihan** [shawnrosofsky/PINO_Applications#2]
Thank you for your sharing. The operation of some files depends on GRF. Can GRF files also be shared?

**Comment by shawnrosofsky** [comment]
The file GRF.py was an old implementation of the Gaussian random fields method.  It was much slower than the method used in solver/my_random_fields.py.  Its functions should not be used in any of the notebooks and any imports to it are old.

I will be doing a code cleanup and all references to the file will be deleted shortly.

**Comment by wongsihan** [comment]
> The file GRF.py was an old implementation of the Gaussian random fields method. It was much slower than the method used in solver/my_random_fields.py. Its functions should not be used in any of the notebooks and any imports to it are old.
> 
> I will be doing a code cleanup and all references to the file will be deleted shortly.

Thanks for your reply!
